name: publish

on:
  push:
    tags:
      - '*'
  pull_request:

env:
  CACHE_DIR: ~/.cache/docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache docker builds
        uses: actions/cache@v2
        with:
          path: |
            $CACHE_DIR
          key: ${{ runner.os }}-${{ hashFiles('dockerfiles/*') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build & Push images
        run: |
          if [ "${{ github.event_name }}" == 'push' ]; then
            if [ "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
              echo "Login registry..."
              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
              echo "Build & Push..."
              IS_PUSH=true CACHE_DIR=$CACHE_DIR bash ./build.sh
            else
              echo "No such secrets, ignored."
            fi
          else
            echo "Build..."
            IS_PUSH=false CACHE_DIR=$CACHE_DIR bash ./build.sh
          fi
