name: Builds and pushes Docker image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build & Push images
        run: |
          if [ "${{ github.event_name }}" == 'push' ]; then
            if [ "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
              echo "Login registry..."
              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
              echo "Build & Push..."
              IS_PUSH=true bash ./build.sh
            else
              echo "No such secrets, ignored."
            fi
          else
            echo "Build..."
            IS_PUSH=false bash ./build.sh
          fi
